# Generated by Django 5.1.6 on 2025-02-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_delete_post_remove_profile_social_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('percent', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
