# Generated by Django 5.1.6 on 2026-04-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Asilbek Sadullayev | Portfolio', max_length=200)),
                ('site_description', models.TextField(default='Asilbek Sadullayev - Backend dasturchi, Django va Python mutaxassisi')),
                ('site_keywords', models.TextField(default='Django, Python, Backend Developer, Portfolio')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Profil rasmi')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon (browser tab rasmi)')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='OG rasmi (Google/ijtimoiy tarmoq preview)')),
                ('preloader_bg', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Kirish sahifasi fon rasmi (preloader)')),
                ('full_name', models.CharField(default='Asilbek Sadullayev', max_length=100)),
                ('first_name', models.CharField(default='Asilbek', max_length=50)),
                ('job_title', models.CharField(default='Backend Dasturchi & API Mutaxassisi', max_length=200)),
                ('typing_phrases', models.TextField(default='Backend Dasturchi\nDjango Mutaxassisi\nPython Ishqibozi\nREST API Yaratuvchi\nTelegram Bot Developer', help_text='Har bir qator alohida jumla (typing animatsiyasi uchun)')),
                ('hero_description', models.TextField(default='Samarali va xavfsiz backend yechimlar yarataman. Django, Python, REST API va Telegram botlar ishlab chiqishda tajribam bor.')),
                ('ready_badge', models.CharField(default='Ishlashga tayyor', max_length=100)),
                ('about_subtitle', models.CharField(default='Backend Dasturchi & API Mutaxassisi', max_length=200)),
                ('about_text_1', models.TextField(default='Men Django va Python texnologiyalarida ixtisoslashgan backend dasturchi. Web dasturlar, REST API va Telegram botlar ishlab chiqishda 2+ yil tajribaga egaman.')),
                ('about_text_2', models.TextField(default="Maqsadim — ishonchli, tezkor va optimallashtirilgan backend yechimlarini taqdim etish. Har bir proyektda kod sifati va xavfsizligiga alohida e'tibor beraman.")),
                ('about_tags', models.TextField(default='Python\nDjango\nREST API\nPostgreSQL\nDocker\nTelegram Bot\nGit\nLinux', help_text='Har bir qator alohida tag (texnologiya nomi)')),
                ('stat_experience', models.CharField(default='2+', max_length=20, verbose_name='Yil tajriba')),
                ('stat_projects', models.CharField(default='15+', max_length=20, verbose_name='Loyihalar soni')),
                ('stat_clients', models.CharField(default='10+', max_length=20, verbose_name='Mijozlar soni')),
                ('stat_quality', models.CharField(default='100%', max_length=20, verbose_name="Sifat ko'rsatkichi")),
                ('phone', models.CharField(default='+998 88 864 88 07', max_length=30)),
                ('contact_email', models.EmailField(default='asilbek.sadullayev000@gmail.com', max_length=254, verbose_name='Aloqa email')),
                ('location', models.CharField(default="Toshkent, O'zbekiston", max_length=100)),
                ('github_url', models.URLField(blank=True, default='https://github.com/ASILBEKasilbek')),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/in/asilbek-sadullayev-4066a3333/')),
                ('telegram_url', models.URLField(blank=True, default='https://t.me/dasturch1_asilbek')),
                ('upwork_url', models.URLField(blank=True, default='https://www.upwork.com/freelancers/~01b6f006f65cc81bac')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/new_digital_world_uz')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='site/', verbose_name='CV/Resume fayl')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Xabar', 'verbose_name_plural': 'Xabarlar'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Loyiha', 'verbose_name_plural': 'Loyihalar'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': "Ko'nikma", 'verbose_name_plural': "Ko'nikmalar"},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
